### ISSUE TITLE
能用TypeScript写一个示例吗？

### ISSUE THREAD

**Issue by soulmachine** [flyingzl/angular2-seed#1]
你的这个例子写的很好，不过美中不足的是，Angular2官方是采用TypeScript了，能否用TypeScript把这个例子重写一遍，这样一个JS版，一个TypeScript版

**Comment by flyingzl** [comment]
例子是采用es6来写的，官方没有强求用户用typescript还是用javascript。其实你用typescript来写，代码也会很类似，因为typescript也是es6的一个超级。

**Comment by flyingzl** [comment]
@soulmachine  `2.0.0-alpha.40` 都已经切换到TypeScript了，所以这次用TypeScript重写了

**Comment by soulmachine** [comment]
谢谢！
