### ISSUE TITLE
有error

### ISSUE THREAD

**Issue by shuxikql** [flyingzl/angular2-seed#5]
运行run start之后就出现error了。。。

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@1.0.0 start: `webpack-dev-server --inline --hot --port 3000 --devtool source-maps --progress --colors --content-base .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@1.0.0 start script 'webpack-dev-server --inline --hot --port 3000 --devtool source-maps --progress --colors --content-base .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --hot --port 3000 --devtool source-maps --progress --colors --content-base .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/angular2/resouces/npm-debug.log

**Comment by flyingzl** [comment]
@shuxikql  你首先得进入`resouces`文件夹，然后运行`npm install`，然后再运行`npm run start`。看看是否有问题。你用的是mac，我在mac下测试通过了的。你应该没在`resources`文件夹里面运行`npm run start`

**Comment by shuxikql** [comment]
好的～非常感谢！希望你继续更新angular2的教程！
